const sampleFormulaERacesData = {
  upcoming: [
      { id: '1', date: 'December 7, 2024', circuit: 'Anhembi Sambadrome Circuit', countryCode: 'BRA' },
      { id: '2', date: 'January 11, 2025', circuit: 'Autódromo Hermanos Rodríguez', countryCode: 'MEX' },
      { id: '3', date: 'January 14, 2025', circuit: 'Jeddah Corniche Circuit', countryCode: 'SAU' },
      { id: '4', date: 'January 15, 2025', circuit: 'Jeddah Corniche Circuit', countryCode: 'SAU' },
      { id: '6', date: 'April 12, 2025', circuit: 'Homestead–Miami Speedway', countryCode: 'USA' },
      { id: '7', date: 'May 4, 2025', circuit: 'CIRCUIT DE MONACO', countryCode: 'MCO' },
      { id: '8', date: 'May 5, 2025', circuit: 'CIRCUIT DE MONACO', countryCode: 'MCO' },
      { id: '9', date: 'May 17, 2025', circuit: 'Tokyo Street Circuit', countryCode: 'JPN' },
      { id: '10', date: 'May 18, 2025', circuit: 'Tokyo Street Circuit', countryCode: 'JPN' },
      { id: '11', date: 'June 1, 2025', circuit: 'Shanghai International Circuit', countryCode: 'CHN' },
      { id: '12', date: 'June 2, 2025', circuit: 'Shanghai International Circuit', countryCode: 'CHN' },
      { id: '13', date: 'June 21, 2025', circuit: 'Jakarta Circuit', countryCode: 'IDN' },
      { id: '14', date: 'July 12, 2025', circuit: 'Tempelhof Airport Street Circuit', countryCode: 'DEU' },
      { id: '15', date: 'July 13, 2025', circuit: 'Tempelhof Airport Street Circuit', countryCode: 'DEU' },
      { id: '16', date: 'July 26, 2025', circuit: 'ExCeL London Street Circuit', countryCode: 'GBR' },
      { id: '17', date: 'July 27, 2025', circuit: 'ExCeL London Street Circuit', countryCode: 'GBR' },
  ],
  past: [
      { id: '1', date: 'January 13, 2024', circuit: 'Autódromo Hermanos Rodríguez', countryCode: 'MEX' },
      { id: '2', date: 'January 26, 2024', circuit: 'Riyadh Street Circuit', countryCode: 'SAU' },
      { id: '3', date: 'January 27, 2024', circuit: 'Riyadh Street Circuit', countryCode: 'SAU' },
      { id: '4', date: 'February 10, 2024', circuit: 'Hyderabad Street Circuit', countryCode: 'IND' },
      { id: '5', date: 'March 16, 2024', circuit: 'Anhembi Sambadrome Circuit', countryCode: 'BRA' },
      { id: '6', date: 'March 30, 2024', circuit: 'Tokyo Street Circuit', countryCode: 'JPN' },
      { id: '7', date: 'April 13, 2024', circuit: 'Misano World Circuit Marco Simoncelli', countryCode: 'ITA' },
      { id: '8', date: 'April 14, 2024', circuit: 'Misano World Circuit Marco Simoncelli', countryCode: 'ITA' },
      { id: '9', date: 'April 27, 2024', circuit: 'CIRCUIT DE MONACO', countryCode: 'MCO' },
      { id: '10', date: 'May 11, 2024', circuit: 'Tempelhof Airport Street Circuit', countryCode: 'DEU' },
      { id: '11', date: 'May 12, 2024', circuit: 'Tempelhof Airport Street Circuit', countryCode: 'DEU' },
      { id: '12', date: 'May 25, 2024', circuit: 'Shanghai International Circuit', countryCode: 'CHN' },
      { id: '13', date: 'May 26, 2024', circuit: 'Shanghai International Circuit', countryCode: 'CHN' },
      { id: '14', date: 'June 29, 2024', circuit: 'Portland International Raceway', countryCode: 'USA' },
      { id: '15', date: 'June 30, 2024', circuit: 'Portland International Raceway', countryCode: 'USA' },
      { id: '16', date: 'July 20, 2024', circuit: 'ExCeL London Street Circuit', countryCode: 'GBR' },
      { id: '17', date: 'July 21, 2024', circuit: 'ExCeL London Street Circuit', countryCode: 'GBR' },
  ],
};

export default sampleFormulaERacesData